# Setup

import os, site, snakemake.shell

cur_env_dir = site.PREFIXES[0]				# set conda environment directory e.g. '~/miniconda2/envs/proj'
snakemake.shell.executable('/bin/bash')		# set snakemake shell executable


# ----------------------------------------------------------------------------------------------- #
# <PROJECTNAME> pipeline
# ----------------------------------------------------------------------------------------------- #


# GLOBAL VARIABLES
# ----------------------------------------------------------------------------------------------- #



# PIPELINE STEPS
# ----------------------------------------------------------------------------------------------- #
